name: Release Deltarune IPA

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0)'
        required: true

jobs:
  package-ipa:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify structure
        run: |
          ls -l Payload/
          ls -l Payload/DELTARUNE.app/

      - name: Create IPA file
        run: |
          cd Payload
          zip -qr ../deltarune.ipa *
          cd ..
          # Verify the IPA was created correctly
          file deltarune.ipa

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Deltarune v${{ github.event.inputs.version }}
          body: |
            Custom Deltarune IPA build
            - Contains latest game files
            - No code signing
          files: deltarune.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
