name: Repackage Deltarune IPA

on:
  workflow_dispatch:

jobs:
  repackage-ipa:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3  # Checks out your repo with Payload/DELTARUNE.app

      - name: Create Payload folder (if not already in repo)
        run: |
          mkdir -p Payload
          # (Optional) If DELTARUNE.app is in root instead of Payload/, move it:
          if [ -d "DELTARUNE.app" ]; then
            mv DELTARUNE.app Payload/
          fi

      - name: Verify structure
        run: |
          ls -l Payload/
          ls -l Payload/DELTARUNE.app/

      - name: Zip into IPA
        run: |
          cd Payload
          zip -qr ../deltarune.ipa *
          cd ..
          echo "IPA file created!"

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Deltarune-Repackaged.ipa
          path: deltarune.ipa
