name: Repackage Deltarune IPA

on:
  workflow_dispatch:

jobs:
  repackage-ipa:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4  # Updated from v3 to v4

      - name: Verify Payload structure
        run: |
          ls -l Payload/
          ls -l Payload/DELTARUNE.app/

      - name: Zip into IPA
        run: |
          cd Payload
          zip -qr ../deltarune.ipa *
          cd ..
          echo "IPA file created!"

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: Deltarune-Repackaged.ipa
          path: deltarune.ipa
