name: Build TrollStore-Compatible IPA

on:
  workflow_dispatch:

jobs:
  build-ipa:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Payload folder
        run: |
          mkdir -p Payload
          mv DELTARUNE.app Payload/ || true  # Moves .app into Payload/

      - name: Fix permissions (critical!)
        run: |
          chmod +x Payload/DELTARUNE.app/UNDERTALE  # Make binary executable
          chmod 755 Payload/DELTARUNE.app  # Fix app folder permissions

      - name: Repack IPA
        run: |
          zip -qr deltarune.ipa Payload
          file deltarune.ipa  # Verify output

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: trollstore-v1.0
          files: deltarune.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
